# Generated by Django 5.2.3 on 2025-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='fase',
            field=models.CharField(choices=[('pre-incubacao', 'Pré-incubação'), ('implantacao', 'Implantação'), ('crescimento', 'Crescimento'), ('consolidacao', 'Consolidação'), ('graduacao', 'Graduação')], default='pre-incubacao', max_length=50, verbose_name='Fase Atual'),
        ),
    ]
