# Generated by Django 5.2.3 on 2025-06-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0002_faseincubacao_statusstartup_startup_responsavel_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="startup",
            name="responsavel",
        ),
        migrations.RemoveField(
            model_name="startup",
            name="status",
        ),
    ]
