# Generated by Django 5.2.3 on 2025-06-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_startup_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='plano',
            field=models.CharField(choices=[('start', 'Start'), ('grow', 'Grow')], default='start', max_length=10, verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='startup',
            name='plataforma_tecnologica',
            field=models.CharField(blank=True, max_length=255, verbose_name='Plataforma Tecnológica'),
        ),
        migrations.AddField(
            model_name='startup',
            name='tipo_incubacao',
            field=models.CharField(choices=[('residente', 'Residente'), ('nao_residente', 'Não Residente')], default='residente', max_length=20, verbose_name='Tipo de Incubação'),
        ),
    ]
