# Generated by Django 5.2.3 on 2025-06-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0003_remove_startup_responsavel_remove_startup_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StatusStartup",
        ),
        migrations.AlterModelOptions(
            name="faseincubacao",
            options={
                "ordering": ["nome"],
                "verbose_name": "Fase de Incubação",
                "verbose_name_plural": "Fases de Incubação",
            },
        ),
        migrations.AlterField(
            model_name="faseincubacao",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
