# Generated by Django 5.2.3 on 2025-06-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_startup_plano_startup_plataforma_tecnologica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='documentacao_pendente',
            field=models.BooleanField(default=False, verbose_name='Documentação Pendente'),
        ),
        migrations.AddField(
            model_name='startup',
            name='rascunho_documentos',
            field=models.TextField(blank=True, null=True, verbose_name='Rascunho de Documentos'),
        ),
    ]
