# Generated by Django 5.2.3 on 2025-06-30 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startup_documentacao_pendente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='financeiro_pendente',
            field=models.BooleanField(default=False, verbose_name='Financeiro Pendente'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor R$')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente')], default='pendente', max_length=10, verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='startups.startup', verbose_name='Startup')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data'],
            },
        ),
    ]
