# Generated by Django 5.2.3 on 2025-06-30 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0005_modeloincubacao_startup_modelo_incubacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="fase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="startups.faseincubacao",
            ),
        ),
    ]
