# Generated by Django 5.2.3 on 2025-06-30 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0006_alter_startup_fase"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoIncubacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="startup",
            name="modelo_incubacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="startups.modeloincubacao",
            ),
        ),
        migrations.AddField(
            model_name="startup",
            name="plano",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="startups.planoincubacao",
            ),
        ),
    ]
