# Generated by Django 5.2.3 on 2025-06-30 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0007_planoincubacao_alter_startup_modelo_incubacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startup",
            name="fase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startup_set",
                to="startups.faseincubacao",
                verbose_name="Fase de Incubação",
            ),
        ),
    ]
