# Generated by Django 5.2.3 on 2025-06-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0009_alter_startup_fase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faseincubacao",
            options={
                "verbose_name": "Fase de Incubação",
                "verbose_name_plural": "Fases de Incubação",
            },
        ),
        migrations.AlterField(
            model_name="faseincubacao",
            name="nome",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Fase de Incubação"
            ),
        ),
    ]
